# Generated by Django 2.2.10 on 2020-11-04 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=255)),
                ('dstate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField()),
                ('hname', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.FloatField()),
                ('t_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Roadways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=30)),
                ('cartype', models.CharField(max_length=20)),
                ('mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Mot')),
            ],
        ),
        migrations.CreateModel(
            name='Railways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_nac', models.CharField(max_length=20)),
                ('c_class', models.CharField(max_length=20)),
                ('mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Mot')),
            ],
        ),
        migrations.CreateModel(
            name='PopularSpots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('cost', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Destination')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Hotel')),
                ('mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Mot')),
            ],
        ),
        migrations.CreateModel(
            name='Luxury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_people', models.IntegerField()),
                ('trip_date', models.DateField()),
                ('total', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Airways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodAC', models.CharField(max_length=20)),
                ('A_class', models.CharField(max_length=20)),
                ('mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Mot')),
            ],
        ),
    ]
