# Generated by Django 3.1 on 2020-11-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularspots',
            old_name='did',
            new_name='d_id',
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(default='Package def', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularspots',
            name='popic',
            field=models.ImageField(blank=True, default='media/h.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
