# Generated by Django 3.1 on 2020-11-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201104_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='review',
            field=models.IntegerField(default=255),
            preserve_default=False,
        ),
    ]
