# Generated by Django 3.1 on 2020-11-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_package_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railways',
            name='mot',
        ),
        migrations.RemoveField(
            model_name='roadways',
            name='mot',
        ),
        migrations.AddField(
            model_name='mot',
            name='A_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mot',
            name='ac_nac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mot',
            name='c_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mot',
            name='cartype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Airways',
        ),
        migrations.DeleteModel(
            name='Railways',
        ),
        migrations.DeleteModel(
            name='Roadways',
        ),
    ]
