# Generated by Django 3.1 on 2020-11-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20201106_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mot',
            name='ac_nac',
        ),
    ]
