# Generated by Django 3.1 on 2020-11-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_mot_ac_nac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='street',
            new_name='locality',
        ),
    ]
