# Generated by Django 3.1 on 2020-11-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20201107_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luxury',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.hotel'),
        ),
    ]
