# Generated by Django 3.1 on 2020-11-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20201107_2123'),
        ('app1', '0008_booking_booking_date'),
    ]

    operations = [
    ]
